GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/5d7a875b0a542230985ca919
###
DELETE http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "sample",
  "number": "123456"
}